version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - STAGE=${STAGE}
      - IS_LOCAL_ENV=1
    ports:
      - "3007:3000"
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run start:dev

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=local_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hhplusServer
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5439:5432"

  redis:
    image: redis:7-alpine
    command: redis-server
    ports:
      - "6386:6379"
