{
  "openapi": "3.0.0",
  "paths": {
    "/": {
      "get": {
        "operationId": "AppController_getHello",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    },
    "/client/me/queue/entries": {
      "post": {
        "operationId": "ClientController_enterEntries",
        "summary": "대기열 진입 요청",
        "parameters": [
          {
            "name": "booking-session-id",
            "in": "header",
            "description": "Booking session id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/EnterEntriesDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/OkResponseDto"
                }
              }
            }
          }
        },
        "tags": [
          "client"
        ],
        "security": [
          {
            "access-token": []
          }
        ]
      }
    },
    "/client/me/queue/entries/{concertDatesId}": {
      "get": {
        "operationId": "ClientController_getEntries",
        "summary": "내 순서 조회",
        "parameters": [
          {
            "name": "concertDatesId",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "booking-session-id",
            "in": "header",
            "description": "Booking session id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetEntriesResDto"
                }
              }
            }
          }
        },
        "tags": [
          "client"
        ],
        "security": [
          {
            "access-token": []
          }
        ]
      }
    },
    "/client/me/point": {
      "get": {
        "operationId": "ClientController_getPoint",
        "summary": "포인트 조회",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Client"
                }
              }
            }
          }
        },
        "tags": [
          "client"
        ],
        "security": [
          {
            "access-token": []
          }
        ]
      }
    },
    "/client/me/point/deposit": {
      "patch": {
        "operationId": "ClientController_addPoint",
        "summary": "포인트 적립",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PatchPointDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Client"
                }
              }
            }
          }
        },
        "tags": [
          "client"
        ],
        "security": [
          {
            "access-token": []
          }
        ]
      }
    },
    "/auth/login": {
      "post": {
        "operationId": "AuthController_signIn",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": ""
          }
        }
      }
    },
    "/client/me/coin": {
      "get": {
        "operationId": "CoinController_getMyCoin",
        "summary": "내 코인 조회",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "description": "Authorization token",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Client"
                }
              }
            }
          }
        },
        "tags": [
          "coin"
        ]
      },
      "post": {
        "operationId": "CoinController_chargeCoin",
        "summary": "코인 충전",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "description": "Authorization token",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CoinLog"
                }
              }
            }
          }
        },
        "tags": [
          "coin"
        ]
      }
    },
    "/concert-dates/{concertDatesId}/seats": {
      "get": {
        "operationId": "SeatController_getAllSeats",
        "summary": "좌석 목록 조회",
        "parameters": [
          {
            "name": "concertDatesId",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "participation-token",
            "in": "header",
            "description": "Participation token",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Seat"
                  }
                }
              }
            }
          }
        },
        "tags": [
          "seat"
        ],
        "security": [
          {
            "access-token": []
          }
        ]
      }
    },
    "/concert-dates/{concertDatesId}/seats/{seatId}/booking": {
      "post": {
        "operationId": "SeatController_bookingSeat",
        "summary": "좌석 예약 요청",
        "parameters": [
          {
            "name": "concertDatesId",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "seatId",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "participation-token",
            "in": "header",
            "description": "Participation token",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Seat"
                }
              }
            }
          }
        },
        "tags": [
          "seat"
        ],
        "security": [
          {
            "access-token": []
          }
        ]
      }
    },
    "/concert-dates/{concertDatesId}/seats/{seatId}/completion": {
      "post": {
        "operationId": "SeatController_completionSeat",
        "summary": "좌석 예약 완료 요청",
        "parameters": [
          {
            "name": "concertDatesId",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "seatId",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "participation-token",
            "in": "header",
            "description": "Participation token",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "booking-session-id",
            "in": "header",
            "description": "Booking session id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CompletionSeatDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Reservation"
                }
              }
            }
          }
        },
        "tags": [
          "seat"
        ],
        "security": [
          {
            "access-token": []
          }
        ]
      }
    }
  },
  "info": {
    "title": "Ticket Server API",
    "description": "Ticket Server API description",
    "version": "0.1",
    "contact": {}
  },
  "tags": [],
  "servers": [],
  "components": {
    "securitySchemes": {
      "access-token": {
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "type": "http",
        "in": "header"
      },
      "booking-session-id": {
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "type": "http",
        "in": "header"
      },
      "participation-token": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "in": "header"
      }
    },
    "schemas": {
      "EnterEntriesDto": {
        "type": "object",
        "properties": {
          "concertDatesId": {
            "type": "string",
            "format": "uuid"
          }
        },
        "required": [
          "concertDatesId"
        ]
      },
      "OkResponseDto": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "ok"
          }
        },
        "required": [
          "message"
        ]
      },
      "GetEntriesResDto": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "WAITING",
              "ATTENDING"
            ]
          },
          "nowNumber": {
            "type": "number"
          },
          "token": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "nowNumber"
        ]
      },
      "Client": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "firstName": {
            "type": "string",
            "format": "string"
          },
          "lastName": {
            "type": "string",
            "format": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "point": {
            "type": "number",
            "default": 0
          },
          "password": {
            "type": "string",
            "format": "string"
          }
        },
        "required": [
          "createdAt",
          "updatedAt",
          "id",
          "firstName",
          "lastName",
          "email",
          "point",
          "password"
        ]
      },
      "PatchPointDto": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "number"
          }
        },
        "required": [
          "amount"
        ]
      },
      "LoginDto": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "required": [
          "email",
          "password"
        ]
      },
      "SeatGrade": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string",
            "enum": [
              "S",
              "A",
              "B",
              "C"
            ]
          },
          "price": {
            "type": "number"
          }
        },
        "required": [
          "createdAt",
          "updatedAt",
          "id",
          "name",
          "price"
        ]
      },
      "Concert": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string",
            "format": "string"
          },
          "artist": {
            "type": "string",
            "format": "string"
          },
          "venue": {
            "type": "string",
            "format": "string"
          },
          "description": {
            "type": "string",
            "format": "string"
          }
        },
        "required": [
          "createdAt",
          "updatedAt",
          "id",
          "name",
          "artist",
          "venue",
          "description"
        ]
      },
      "ConcertDates": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "concertDate": {
            "format": "date-time",
            "type": "string"
          },
          "reserveDate": {
            "format": "date-time",
            "type": "string"
          },
          "concert": {
            "$ref": "#/components/schemas/Concert"
          }
        },
        "required": [
          "createdAt",
          "updatedAt",
          "id",
          "concertDate",
          "reserveDate",
          "concert"
        ]
      },
      "Seat": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "section": {
            "type": "string",
            "format": "string"
          },
          "row": {
            "type": "string",
            "format": "string"
          },
          "number": {
            "type": "number"
          },
          "isBooked": {
            "type": "boolean",
            "default": false
          },
          "seatGrade": {
            "$ref": "#/components/schemas/SeatGrade"
          },
          "concertDates": {
            "$ref": "#/components/schemas/ConcertDates"
          }
        },
        "required": [
          "createdAt",
          "updatedAt",
          "id",
          "section",
          "row",
          "number",
          "isBooked",
          "seatGrade",
          "concertDates"
        ]
      },
      "Reservation": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "address": {
            "type": "string",
            "format": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "DONE",
              "CANCEL"
            ]
          },
          "client": {
            "$ref": "#/components/schemas/Client"
          },
          "seat": {
            "$ref": "#/components/schemas/Seat"
          }
        },
        "required": [
          "createdAt",
          "updatedAt",
          "id",
          "address",
          "status",
          "client",
          "seat"
        ]
      },
      "CoinLog": {
        "type": "object",
        "properties": {
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "eventType": {
            "type": "string",
            "enum": [
              "CHARGE",
              "REDUCE",
              "REFUND"
            ]
          },
          "point": {
            "type": "number",
            "default": 0
          },
          "client": {
            "$ref": "#/components/schemas/Client"
          },
          "reservation": {
            "$ref": "#/components/schemas/Reservation"
          }
        },
        "required": [
          "createdAt",
          "updatedAt",
          "id",
          "eventType",
          "point",
          "client"
        ]
      },
      "CompletionSeatDto": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          }
        },
        "required": [
          "address"
        ]
      }
    }
  }
}